name: Build Firmware
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install QMK
        run: pip3 install qmk
      - name: Setup QMK
        run: qmk setup -y
      - name: Compile
        run: qmk compile -kb handwired/antari -km default
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: my_firmware
          path: ./*.uf2
