name: Build Firmware
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile Firmware
        run: |
          qmk setup -y
          qmk compile -kb handwired/antari -km default

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: antari_firmware
          path: ./*.uf2
