name: QMK Compile
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install qmk

      - name: Compile Firmware
        run: |
          # Thiết lập môi trường QMK ngay tại thư mục repo
          export QMK_HOME=$(pwd)
          qmk setup -y
          
          # Lệnh biên dịch chính xác cho bàn phím của bạn
          qmk compile -kb handwired/antari -km default

      - name: Export Firmware
        uses: actions/upload-artifact@v4
        with:
          name: antari_firmware
          path: |
            *.uf2
            *.bin
            *.hex
