name: QMK Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - run: git config --global --add safe.directory '*'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          export QMK_HOME=$(pwd)
          qmk compile -kb handwired/antari -km default
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            *.uf2
            *.bin
            *.hex
